### ISSUE TITLE
Add configuration via file

### ISSUE THREAD

**Issue by sethbattin** [sethbattin/bundle-report#5]
## Feature
In addition to the [CLI options](https://github.com/sethbattin/bundlesize/blob/parallel-dev/src/input.js#L3) and the [package.json object](https://github.com/sethbattin/bundlesize/blob/parallel-dev/src/config.js#L10), we should permit loading a configuration file.

- Open-ended configuration
- Tidy package.json
- Clean CLI
- Settings in version control

### Requirements

Comments welcome :)

1. In the absence of any CLI arg or package.json setting, we should check for a default config file such as `.bundlesize.rc`.
2. Create an in-repo default config, and use that in place of [hardcoding the defaults into config](https://github.com/sethbattin/bundlesize/blob/parallel-dev/src/config.js#L36).
3. The CLI should accept a `-c, --config [config]` option and try to read it (also format inferred or agnostic).
4. Check if package.json's `bundlesize` key is a string, and if so try it as a file path.
5. Check the `bundlesize` object property in package.json for a key 'config'.  If there are other config settings there, merge the file settings over the package.json settings (allows local overrides)

### File format
Any of these:

- JS module
- JSON
- yaml
- other?

I vote for being format agnostic.  If the file name extension isn't obvious, we should `try/catch` js and json via `require`, yaml via a yml loader, and {other} via whatever is appropriate.  If we're taking a customer's file and parsing it, we can try to guess correctly based on extension and save a few caught exceptions.

**Comment by sethbattin** [comment]
@bkd705, I saw you made a big start on this over on the main repo.  Would you interested in trying to merge that over here?  If not, would it be alright I tried to cherry-pick your commits?

Sorry for the random @, I figured this was more relevant to the conversation than linkedin.  :)

**Comment by threehams** [comment]
JS+JSON+YML is nearly universal at this point. I would bet there's a library that already handles the three formats in a unified way.

**Comment by sethbattin** [comment]
Resolved in https://github.com/sethbattin/bundle-report/releases/tag/v1.2.0
